//WAP to calculate the total revenue generated by a business over three months. Prompt the user to enter the monthly revenue figures, then display the total revenue.

const readlineSync = require('readline-sync');


let totalRevenue = 0;


let month1Revenue = readlineSync.questionFloat(readlineSync.question('Enter the revenue for month 1: '));
let month2Revenue = readlineSync.questionFloat(readlineSync.question('Enter the revenue for month 2: '));
let month3Revenue = readlineSync.questionFloat(readlineSync.question('Enter the revenue for month 3: '));


totalRevenue = month1Revenue + month2Revenue + month3Revenue;


console.log('Total revenue generated over three months:', totalRevenue.toFixed(2));